name: ${pluginName}
version: ${version}
main: com.willfp.stattrackers.StatTrackersPlugin
api-version: 1.19

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false


permissions:
  stattrackers.*:
    description: All stattrackers permissions
    default: op
    children:
      stattrackers.command.reload: true
      stattrackers.command.give: true
      stattrackers.command.stattrackers: true

  stattrackers.command.stattrackers:
    description: Allows the use of /stattrackers to open the editor
    default: true
  stattrackers.command.reload:
    description: Allows reloading the config
    default: op
  stattrackers.command.give:
    description: Allows the use of /stattrackers give to give a player a stat tracker
    default: op